spec:
  replicas: 1
  imagePullSecrets: ""

config:
  connectionStrings:
    postgres: ""
  jwt:
    audience: ""
    authority: ""
  auth0:
    domain: ""
    clientId: ""
    clientSecret: ""
  rabbitmq:
    hostName: ""
    userName: ""
    password: ""
    virtualHost: ""

