spec:
  replicas: 1
  imagePullSecrets: ""

config:
  connectionStrings:
    postgres: ""
  jwt:
    audience: ""
    authority: ""
    issuer: ""
  auth0:
    domain: ""
    clientId: ""
    clientSecret: ""
