version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    volumes:
        - cms_usermanagement_rabbitmq_data:/var/lib/rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - cms_usermanagement_postgres_data:/var/lib/postgresql/data
volumes:
  cms_usermanagement_rabbitmq_data:
    driver: local
  cms_usermanagement_postgres_data:
    driver: local
