version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    volumes:
        - cms_usermanagement_rabbitmq_data:/var/lib/rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - cms_usermanagement_postgres_data:/var/lib/postgresql/data

  # https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub
  azure-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - cms_usermanagement_azure_blob_storage_data:/data

  azure-cli:
    depends_on:
      - azure-blob-storage
    image: mcr.microsoft.com/azure-cli

    command: >
      az storage container create -n user-profile-images --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-blob-storage:10000/devstoreaccount1;QueueEndpoint=http://azure-blob-storage:10001/devstoreaccount1;"

volumes:
  cms_usermanagement_rabbitmq_data:
    driver: local
  cms_usermanagement_postgres_data:
    driver: local
  cms_usermanagement_azure_blob_storage_data:
    driver: local
