apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
data:
  appsettings.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "ConnectionStrings": {
            "Postgres": {{ .Values.config.connectionStrings.postgres | quote }}
        },
        "Jwt": {
            "Audience": {{ .Values.config.jwt.audience | quote }},
            "Authority": {{ .Values.config.jwt.authority | quote }}
        },
        "Auth0": {
            "Domain": {{ .Values.config.auth0.domain | quote }},
            "ClientId": {{ .Values.config.auth0.clientId | quote }},
            "ClientSecret": {{ .Values.config.auth0.clientSecret | quote }}
        },
        "RabbitMq": {
            "HostName": {{ .Values.config.rabbitmq.hostName | quote }},
            "UserName": {{ .Values.config.rabbitmq.userName | quote }},
            "Password": {{ .Values.config.rabbitmq.password | quote }},
            "VirtualHost": {{ .Values.config.rabbitmq.virtualHost | quote }}
        }
    }