apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        service: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: tliscr.azurecr.io/cms-user-management:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /app/appsettings.json
            name: config
            subPath: appsettings.json
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}